server:
  port: 8181
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/nmsl?serverTimezone=UTC
    username : root
    password : 142857
    driverClassName : com.mysql.cj.jdbc.Driver
  jpa:
    database : MYSQL
    show-sql : true
    hibernate:
      ddl-auto : update
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        event:
          merge:
            entity_copy_observer: allow

